dist: xenial
language: python
python:
- '3.7'
services:
- docker
before_install:
- pip install pipenv
install:
- pipenv sync
stages:
- black
- test
- build
- name: deploy-prod
  if: head_branch IS blank AND tag IS present
- name: deploy-staging
  if: head_branch IS blank AND tag is blank
before_script:
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then export TAG=latest; else export TAG="pr-$TRAVIS_PULL_REQUEST_BRANCH";
  fi
jobs:
  include:
  - stage: black
    install: pip install black
    script: black --check .
  - stage: test
    install:
    - pipenv sync --dev
    - pip install coveralls
    script:
    - pytest
    after_success:
    - coveralls
  - stage: build
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
  - stage: deploy-prod
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_REGISTRY:$TAG;
    deploy:
      provider: heroku
      app: "$HEROKU_APP"
      api_key: "$HEROKU_AUTH_KEY"
      on:
        branch: master
  - stage: deploy-staging
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_REGISTRY:$TAG;
    deploy:
      provider: heroku
      app: "$HEROKU_APP_STAGING"
      api_key: "$HEROKU_AUTH_KEY"
      on:
        branch: master
        tags: true
branches:
  only:
  - master
notifications:
  slack: $SLACK_TRAVIS_TOKEN
    on_success: always