dist: xenial
language: python
python:
  - '3.7'

before_install:
  - pip install pipenv
install:
  - pipenv sync

stages:
  - black
  - test
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: black
      install: pip install black
      script: black --check .

    - stage: test
      install:
        - pipenv sync --dev
        - pip install coveralls
      script:
        - pytest
      after_success:
        - coveralls

branches:
  only:
    - master
