dist: xenial
language: python
python:
- '3.7'
services:
- docker
before_install:
- pip install pipenv
install:
- pipenv sync
stages:
- black
- test
- build
- deploy
before_script:
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then export TAG=latest; else export TAG="pr-$TRAVIS_PULL_REQUEST_BRANCH";
  fi
jobs:
  include:
  - stage: black
    install: pip install black
    script: black --check .
  - stage: test
    install:
    - pipenv sync --dev
    - pip install coveralls
    script:
    - pytest
    after_success:
    - coveralls
  - stage: build
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
  - stage: deploy
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_REGISTRY:$TAG;
    if: tag IS present
    on:
      tags: true
    deploy:
      provider: heroku
      app: "$HEROKU_APP"
      api_key: "$HEROKU_AUTH_KEY"
  - stage: deploy
    script:
    - docker build -t $DOCKER_REGISTRY:$TAG .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_REGISTRY:$TAG;
    if: branch= master
    deploy:
      provider: heroku
      app: "$HEROKU_APP_STAGING"
      api_key: "$HEROKU_AUTH_KEY"
branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  slack:
    on_pull_request: true
    on_success: true
    on_failure: true
    secure: xGAfs2CBdYv+Degir7Tlif6VNCJxu/w9zne0skM7VeC1ncnhD8NYwv3/7VN4JgaeMv4gdoZUppEmuLIlapsXRO1KORuVlT7AabPufmxF+mC94wfQ+/jmOvRYoeNd5CtFcE64JDs5snnd6i6kKCfgKm+hFLmyXDhb9ljbH+JTXDyKwOOZm89z4stf84mVDm8xQXAmpT4VX+40GfkBGFsfS4AcB7mMFRkEzP0jL2Rp6F6HPobIcIGusZ1Ec+sRTRM4RBGKNuq75/KhNtND7TDw9QOrtlG3z1Q5+9bclr8AAR8Zi+dxpdWwB2Vzac5sDMaATcWVrucN28mNyQo28i6GdCciGm6zv1jQJfOr4HpFeCxru3KfuUNVFOvBoAYmOGrkGIoJAZh3+QWRUQl9zsl2uNb0iRXQSbjgD8nAPSCom1r6IgjQslHVce19syVBGioRacXSsHd5N7Eyx0yq6s8mFvbeP38r1WdbujKCkqBmtJ1ER7kR3ocepzNA0/QvasZPQijBgL/h4OtX9N+crf+Z0mTY5a87b/a32AF0jRlA+POyCC9/oGX6d81qVCm6R/rgWr6/E43eeY/PKuhuYDV24KxXfhtL4D0SgUatdYbxqU4RkMa7B4C5WT3N2krW+l2DY6kSgZNYSgfvAg0mLn26HKMbkj3tyLkCvvq+h7DdyU8=
