version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  turbot:
    build: .
    restart: always
    command: ./entrypoint.sh
    environment:
      DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:5000 --workers=4"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres-data:
