version: '3'

services:
  postgres:
    image: postgres

  turbot:
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "psql://postgres:postgres@postgres:5432/postgres"
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:8000 --workers=4"
