# Generated by Django 2.2.1 on 2020-01-26 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_auto_20190714_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
