# Generated by Django 3.0.2 on 2020-03-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_poll_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll", options={"ordering": ["-created_at"]},
        ),
    ]
