# Generated by Django 3.0.5 on 2020-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_auto_20200313_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="open_choice",
            field=models.BooleanField(default=False),
        ),
    ]
