# Generated by Django 3.0.5 on 2020-05-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_poll_open_choice"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="choice", name="index_in_bounds",),
    ]
