name: CI

on: [push, pull_request]    

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: . --check
    - name: Install requirements
      uses: peaceiris/actions-pipenv@3.6
      with:
        args: sync --dev
    - name: Pytest
      uses: cclauss/GitHub-Action-for-pytest@0.0.2
      with:
        args: pytest
